### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by FatBoyXPC** [jfly/shtuff#9]

**Comment by FatBoyXPC** [comment]
Well...we really suck at coming back to issues...I guess I'll resurrect this with a (potentially?!) new intermittent failure!

```
(nix:nix-shell-env) [james@livtechthinkpad shtuff]$ make test
python -m unittest
.......E.......
======================================================================
ERROR: test_shtuff_exit (tests.test_shtuff.TestShtuff.test_shtuff_exit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/james/dev/shtuff/tests/test_shtuff.py", line 93, in test_shtuff_exit
    receiver.expect("exit")
  File "/nix/store/ihgp727i13cv4qamp4isj1apy4rlrjzc-python3.11-pexpect-4.9.0/lib/python3.11/site-packages/pexpect/spawnbase.py", line 354, in expect
    return self.expect_list(compiled_pattern_list,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ihgp727i13cv4qamp4isj1apy4rlrjzc-python3.11-pexpect-4.9.0/lib/python3.11/site-packages/pexpect/spawnbase.py", line 383, in expect_list
    return exp.expect_loop(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ihgp727i13cv4qamp4isj1apy4rlrjzc-python3.11-pexpect-4.9.0/lib/python3.11/site-packages/pexpect/expect.py", line 179, in expect_loop
    return self.eof(e)
           ^^^^^^^^^^^
  File "/nix/store/ihgp727i13cv4qamp4isj1apy4rlrjzc-python3.11-pexpect-4.9.0/lib/python3.11/site-packages/pexpect/expect.py", line 122, in eof
    raise exc
pexpect.exceptions.EOF: End Of File (EOF). Exception style platform.
<pexpect.pty_spawn.spawn object at 0x7ffff70ce550>
command: /nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/bin/python
args: ['/nix/store/glfr70gi7hfaj50mwj2431p8bg60fhqw-python3-3.11.9/bin/python', '-c', 'import shtuff; shtuff.main()', 'as', 'receiver']
buffer (last 100 chars): b''
before (last 100 chars): b'\r\n'
after: <class 'pexpect.exceptions.EOF'>
match: None
match_index: None
exitstatus: None
flag_eof: True
pid: 1623269
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'exit')

----------------------------------------------------------------------
Ran 15 tests in 12.320s

FAILED (errors=1)
make: *** [Makefile:3: test] Error 1
```
